### ISSUE TITLE
Improve map coloring

### ISSUE THREAD

**Issue by brmagnuson** [ucd-cws/drought-app#3]
Right now, shortages show up as empty shapes outlined in black lines, while met demand shows up as shapes filled with blue. The empty shapes don't stand out. Please change the coloring so that the the shortages stand out (perhaps a blue to red continuum?).

**Comment by jrmerz** [comment]
@qjhart So we had investigated this.  I believe the issue is that we use opacity to currently indicate percent of demand.  We decided this because applying opacity allowed us to see more markers at or around the same location (specially when a marker is next to a large demand). Giving markers opacity always has the draw back of the markers changing color based on the basemap.  The mix of both opacity and color gradient on a verying background (basemap) was confusing.  Due to these constraints, we removed the color gradient and left the demand blue unless unless 0, then black.

Ideas and suggestions are welcome.  Perhaps red if 0, otherwise blue with varying opacity?

**Comment by brmagnuson** [comment]
What if we stick with using opacity but use red instead to indicate shortage, rather than blue to indicate met demand, and vary opacity to indicate how bad the shortage is? So red at zero percent of demand, less red at higher percentages of demand, and greyed out for 100% of demand. 

Also, then the zero demand places could be the hollow shapes with no color inside, just the outline.

**Comment by brmagnuson** [comment]
Actually, after some further discussion, allowing the user to toggle between the current view (blue, most emphasizes users who get 100% of demand to show met demand) and the view I described above (red, most emphasizes users who get 0% of demand to show shortage) would be ideal. Shortage should be the default view, but if they could switch to show met demand if that's what they were interested in, it would be really great. Is this possible?

**Comment by jrmerz** [comment]
That should be possible.  I will work on putting something together.

**Comment by brmagnuson** [comment]
Wonderful; thanks!

**Comment by jrmerz** [comment]
I have pushed a first pass.  You can toggle between the two different rendering styles in the legend, under percent of demand.

**Comment by brmagnuson** [comment]
This is looking good; thank you. Could we switch it so that render as shortage is default, please?

**Comment by jrmerz** [comment]
not a problem. updated.

**Comment by qjhart** [comment]
@brmagnuson, good suggestions.  I think this is a nice addition.

**Comment by brmagnuson** [comment]
I showed this to the others today; everyone is happy with the new coloring and toggle option.
